import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
const __dirname = dirname(fileURLToPath(import.meta.url))
const qPath = join(__dirname, '../src/data/questions.json')
const existing = JSON.parse(readFileSync(qPath, 'utf8'))
const startId = Math.max(...existing.map(q => (typeof q.id === 'number' ? q.id : 0))) + 1

const newQuestions = [
  {
    id: startId,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Get or connect to data",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Prepare the data > Get or connect to data",
    commonTrap: "Confusing 'Get Data' with 'Load Data'",
    trapType: "UI Navigation",
    question: "I want to add a new data source into my existing Power BI file. What option do I need to go to?",
    choices: ["Load Data", "Get Data", "Open Data", "Find Data"],
    correctAnswers: [1],
    explanation: "In Power BI Desktop, 'Get Data' is the entry point for connecting to any data source. It is found on the Home tab.",
    estimatedTimeSeconds: 45,
    tags: ["Power BI Desktop", "Data Source", "Get Data"]
  },
  {
    id: startId + 1,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Create reports",
    commonTrap: "Confusing Focus mode with Zoom mode",
    trapType: "UI Feature Naming",
    question: "When I have selected a visual, I can click on an icon that magnifies the visual (shows it bigger, without any other visuals showing). What is this icon called?",
    choices: ["Data mode", "Focus mode", "Zoom mode", "Expand"],
    correctAnswers: [1],
    explanation: "Focus mode enlarges a single visual to fill the entire canvas. You can exit Focus mode by clicking 'Back to report'.",
    estimatedTimeSeconds: 45,
    tags: ["Focus Mode", "Visuals", "Report Canvas"]
  },
  {
    id: startId + 2,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Create reports",
    commonTrap: "Thinking the visual must be deselected first",
    trapType: "UI Workflow",
    question: "I have added a table visual to my existing Power BI file. I want to change it to a stacked bar chart. What is one way of doing this?",
    choices: [
      "Ensure that no visual is selected, then go to Home - Insert - Stacked bar chart.",
      "Ensure that no visual is selected, go to the Data/Fields pane, click on the fields, and select 'stacked bar chart'.",
      "Ensure the visual is selected, and go to 'Build a Visual'/Visualization pane, and click on 'stacked bar chart'.",
      "Ensure the visual is selected, and go to Data/Fields pane, and click on 'stacked bar chart'."
    ],
    correctAnswers: [2],
    explanation: "To change a visual type, the visual must be selected. You then go to the Visualization pane (Build a Visual) and click the desired chart type.",
    estimatedTimeSeconds: 60,
    tags: ["Visual Types", "Visualization Pane", "Stacked Bar Chart"]
  },
  {
    id: startId + 3,
    type: "single",
    domain: "Manage and secure Power BI",
    subtopic: "Create and manage workspaces and assets",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Manage and secure Power BI > Publish, import, or update items in a workspace",
    commonTrap: "Thinking 'Share' or 'Upload' is the correct menu option",
    trapType: "UI Navigation",
    question: "I want to add my existing report to the Power BI Service. What option do I go to?",
    choices: [
      "File - Publish - Publish to Power BI",
      "File - Upload - Upload to Power BI",
      "File - Share - Share to Power BI",
      "File - Move - Move to Power BI"
    ],
    correctAnswers: [0],
    explanation: "To publish a report from Power BI Desktop to the Power BI Service, go to File > Publish > Publish to Power BI. You can also use the Publish button on the Home tab.",
    estimatedTimeSeconds: 45,
    tags: ["Publish", "Power BI Service", "Power BI Desktop"]
  },
  {
    id: startId + 4,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Prepare the data > Transform and load the data > Select appropriate column data types",
    commonTrap: "Assuming Image is a valid data type because Binary is",
    trapType: "Data Type Knowledge",
    question: "Which of the following is NOT a valid data type for a field in Power BI?",
    choices: ["Whole number", "Image", "Date/time", "Text"],
    correctAnswers: [1],
    explanation: "Image is not a valid data type in Power BI. Valid types include Whole number, Decimal number, Fixed decimal number, Date/time, Date, Time, Text, True/False, and Binary.",
    estimatedTimeSeconds: 60,
    tags: ["Data Types", "Power BI Desktop", "Fields"]
  },
  {
    id: startId + 5,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Going to the Data pane or Format pane instead of the Visualization pane",
    trapType: "UI Navigation",
    question: "I have created a visual which includes 'Sum of SalesVolume'. I wish to change the aggregation from Sum to Average for this visual only. How can I do this?",
    choices: [
      "Click on the field in the Data pane, and go to Column tools.",
      "Select the visual, and go to the 'Build a visual'/Visualization pane.",
      "Select the visual, and right-hand click on the visualization.",
      "Select the visual, and go to the Format pane."
    ],
    correctAnswers: [1],
    explanation: "To change the aggregation for a specific visual, select the visual and go to the Build a Visual/Visualization pane. You can then right-click on the field or click the arrow next to it to change the aggregation.",
    estimatedTimeSeconds: 60,
    tags: ["Aggregation", "Visualization Pane", "Measures"]
  },
  {
    id: startId + 6,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Looking for a 'Copy Formatting' right-click option",
    trapType: "UI Feature Naming",
    question: "I have two visuals. I have fully formatted the first visual. I wish to copy the formatting from the first visual to the second. How can I do this?",
    choices: [
      "Click on the first visual, select Home - Format Painter, and click on the second visual.",
      "Click on the first visual, select Home - Format Special - Formats, and click on the second visual.",
      "Click on the first visual, select Home - Copy, click on the second visual, and select Paste - Formats.",
      "Right-hand click on the first visual, select Copy - Copy Formatting, and click on the second visual."
    ],
    correctAnswers: [0],
    explanation: "Format Painter in the Home tab allows you to copy formatting from one visual and apply it to another by clicking the target visual.",
    estimatedTimeSeconds: 60,
    tags: ["Format Painter", "Visual Formatting", "Home Tab"]
  },
  {
    id: startId + 7,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Create reports",
    commonTrap: "Using double-click or right-click instead of Ctrl+click",
    trapType: "UI Interaction",
    question: "I want to select two visuals at the same time. I click on the first visual. How do I select the second visual?",
    choices: [
      "Double-click on the second visual",
      "Right-hand click on this second visual",
      "Hold down Control and click on the second visual",
      "Hold down Alt and click on the second visual"
    ],
    correctAnswers: [2],
    explanation: "Hold down Ctrl (Control) and click on the second visual to select both visuals simultaneously. You can also use Shift+click to select both visuals.",
    estimatedTimeSeconds: 45,
    tags: ["Multiple Selection", "Visuals", "Report Canvas"]
  },
  {
    id: startId + 8,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Thinking Line and clustered bar chart is a standard single visual",
    trapType: "Visual Type Knowledge",
    question: "Which of these is a standard visual which you can select in the 'Build a visual'/Visualization pane? Note - this is a single visual, not two different visuals.",
    choices: [
      "Line and clustered bar chart",
      "Line and pie chart",
      "Line chart and table",
      "Line and stacked column chart"
    ],
    correctAnswers: [3],
    explanation: "The 'Line and stacked column chart' is a standard combined visual in Power BI. You can also use a 'Line and clustered column chart'. There is no built-in 'Line and pie chart' or 'Line chart and table' combined visual.",
    estimatedTimeSeconds: 60,
    tags: ["Visual Types", "Combo Chart", "Visualization Pane"]
  },
  {
    id: startId + 9,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "understanding",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Confusing stacked column chart with clustered column chart",
    trapType: "Visual Type Identification",
    question: "A visual shows years 2000-2016 along the X-axis, Sales Volume on the Y-axis, and a series of bars in different colors for each region stacked on top of each other per year. What type of visual is this?",
    choices: [
      "Clustered column chart",
      "Stacked column chart",
      "Clustered bar chart",
      "Stacked bar chart"
    ],
    correctAnswers: [1],
    explanation: "A stacked column chart shows vertical bars with segments stacked on top of each other, each segment representing a category (e.g., region). A clustered column chart would show separate bars side by side.",
    estimatedTimeSeconds: 60,
    tags: ["Stacked Column Chart", "Visual Types", "Chart Identification"]
  },
  {
    id: startId + 10,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Configure drillthrough navigation",
    commonTrap: "Thinking only the selected year expands, not all years",
    trapType: "Hierarchy Drill Behavior",
    question: "I have a matrix which has the OrderDate hierarchy in the rows section. It is currently showing the Years 2023 to 2025. What happens if I click on the year 2024, then click on 'Expand all down one level in the hierarchy'?",
    choices: [
      "All of the years in the OrderDate field will be expanded to the Year and Month hierarchy.",
      "All of the years in the OrderDate field will be expanded to the Year and Quarter hierarchy.",
      "The 2024 year only will be expanded into months. The other years will remain as years.",
      "Instead of showing OrderDate years, it will show Quarters instead."
    ],
    correctAnswers: [1],
    explanation: "'Expand all down one level' expands ALL rows down one level in the hierarchy — not just the selected row. In a standard date hierarchy, below Year is Quarter, so all years expand to show quarters.",
    estimatedTimeSeconds: 90,
    tags: ["Matrix", "Hierarchy", "Expand", "Date Hierarchy"]
  },
  {
    id: startId + 11,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "understanding",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Thinking both table and matrix can summarise data",
    trapType: "Visual Capability",
    question: "What is the difference between a table and a matrix in Power BI?",
    choices: [
      "A table can summarise data. A matrix cannot summarise data.",
      "A table cannot summarise data. A matrix can summarise data.",
      "A table has a fixed number of columns. A matrix has a variable number of columns.",
      "A table has a variable number of columns. A matrix has a fixed number of columns."
    ],
    correctAnswers: [2],
    explanation: "A table has a fixed column for each field in the columns area. A matrix has a column for the rows area, plus columns for each unique value in the column fields — making its number of columns variable.",
    estimatedTimeSeconds: 60,
    tags: ["Table Visual", "Matrix Visual", "Visual Comparison"]
  },
  {
    id: startId + 12,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Configure sync slicers",
    commonTrap: "Confusing Sync Slicers with Edit Interactions",
    trapType: "Feature Confusion",
    question: "What does Sync Slicers do?",
    choices: [
      "It allows a single slicer to affect multiple pages.",
      "It allows you to choose which visuals on the same page are affected by the slicer.",
      "It allows you to format the style of the slicer."
    ],
    correctAnswers: [0],
    explanation: "Sync Slicers (View > Sync Slicers) allows a slicer on one page to filter visuals on other pages. You can also control whether the slicer is visible on those other pages.",
    estimatedTimeSeconds: 60,
    tags: ["Sync Slicers", "Slicers", "Cross-page Filtering"]
  },
  {
    id: startId + 13,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "understanding",
    examObjective: "Visualize and analyze the data > Apply slicing and filtering",
    commonTrap: "Thinking slicer affects all pages by default",
    trapType: "Slicer Default Scope",
    question: "I have just created a slicer on a page which has 3 other visuals. By default, what visuals does this slicer affect?",
    choices: [
      "The nearest visual to the slicer.",
      "The visuals that you choose in the Format pane.",
      "All visuals on that page.",
      "All visuals in the report (all pages)."
    ],
    correctAnswers: [2],
    explanation: "By default, a slicer affects all visuals on the same page. To extend it to other pages, you use View - Sync Slicers.",
    estimatedTimeSeconds: 60,
    tags: ["Slicers", "Filter Scope", "Report Pages"]
  },
  {
    id: startId + 14,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Apply slicing and filtering",
    commonTrap: "Confusing ? with * or % wildcard characters",
    trapType: "Wildcard Syntax",
    question: "I want to create an Advanced Filter. Which of these is a wildcard I can use which represents exactly one character?",
    choices: ["*", "_", "?", "%"],
    correctAnswers: [2],
    explanation: "In Advanced Filters, '?' represents exactly one character, and '*' represents zero, one or multiple characters.",
    estimatedTimeSeconds: 60,
    tags: ["Advanced Filter", "Wildcards", "Filters Pane"]
  },
  {
    id: startId + 15,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Apply slicing and filtering",
    commonTrap: "Using Basic filtering when conditions like 'contains' are needed",
    trapType: "Filter Type Selection",
    question: "I go to View - Filters and can see 'Filters on this visual', 'Filters on this page' and 'Filters on all pages'. I want to add a filter that shows only those Region Names which contain 'East' or 'Midlands', and the filter should automatically update when data changes. Which Filter Type should I use?",
    choices: ["Basic filtering", "Advanced filtering", "Top N", "Relative date"],
    correctAnswers: [1],
    explanation: "Advanced filtering allows conditions such as 'contains', 'greater than', and 'is not blank'. Basic filtering only provides checkboxes for specific values.",
    estimatedTimeSeconds: 75,
    tags: ["Advanced Filter", "Filter Types", "Filters Pane"]
  },
  {
    id: startId + 16,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Group and layer visuals by using the Selection pane",
    commonTrap: "Going to Format pane instead of Selection pane",
    trapType: "UI Navigation",
    question: "I want to hide a visual. Which pane do I go to?",
    choices: ["The Format pane", "The Bookmarks pane", "The Sync Slicers pane", "The Selection pane"],
    correctAnswers: [3],
    explanation: "The Selection pane (View > Selection) allows you to hide visuals, change their layer order, and manage tab order for accessibility.",
    estimatedTimeSeconds: 45,
    tags: ["Selection Pane", "Hide Visual", "Report Canvas"]
  },
  {
    id: startId + 17,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Configure bookmarks",
    commonTrap: "Thinking bookmarks save the data source",
    trapType: "Bookmark Capability",
    question: "Which of the following do bookmarks NOT do?",
    choices: [
      "Save data sources",
      "Save filter, drill and sort state",
      "Save visual display state",
      "Save the current page"
    ],
    correctAnswers: [0],
    explanation: "Bookmarks capture the state of a report page including filters, visuals, slicers, and page visibility — but they do NOT save data sources.",
    estimatedTimeSeconds: 60,
    tags: ["Bookmarks", "Report State", "Filters"]
  },
  {
    id: startId + 18,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Putting the field in Legend instead of Small multiples",
    trapType: "Visual Field Placement",
    question: "I want to change a stacked bar chart visual so that, instead of showing one bar chart, it shows many charts, one for each Department. Where do I put the Department field?",
    choices: [
      "In the Y-axis area",
      "In the Legend area",
      "In the Small multiples area",
      "In the Tooltips area"
    ],
    correctAnswers: [2],
    explanation: "Dragging a field into the Small multiples area creates a separate chart for each value of that field. Legend would color-code within a single chart.",
    estimatedTimeSeconds: 60,
    tags: ["Small Multiples", "Visual Configuration", "Stacked Bar Chart"]
  },
  {
    id: startId + 19,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Apply sorting to visuals",
    commonTrap: "Looking for a dedicated Sort button or going to View menu",
    trapType: "UI Navigation",
    question: "I want to sort data descending in a visual. What do I do to achieve this?",
    choices: [
      "Click on the ↓ down arrow next to a visual.",
      "Click on the ... next to a visual",
      "Go to View - Sort.",
      "Go to the Format pane."
    ],
    correctAnswers: [1],
    explanation: "To sort a visual, click on the '...' (more options) icon next to the visual, then go to Sort by to change the sort field and direction.",
    estimatedTimeSeconds: 45,
    tags: ["Sorting", "Visuals", "More Options Menu"]
  },
  {
    id: startId + 20,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Configure navigation for a report",
    commonTrap: "Looking in Insert - Shapes instead of Insert - Buttons",
    trapType: "UI Navigation",
    question: "Where can you add a bookmark navigator?",
    choices: [
      "In the Home menu - you can insert it like any visual.",
      "In the Insert menu - Buttons",
      "In the Insert menu - Shapes",
      "In the Modeling menu"
    ],
    correctAnswers: [1],
    explanation: "A bookmark navigator is found under Insert > Buttons. It creates a button group that navigates between bookmarks.",
    estimatedTimeSeconds: 45,
    tags: ["Bookmark Navigator", "Buttons", "Navigation"]
  },
  {
    id: startId + 21,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "analysis",
    examObjective: "Visualize and analyze the data > Configure navigation for a report",
    commonTrap: "Thinking Text Boxes support Action types like Buttons do",
    trapType: "UI Object Capability",
    question: "Using the 'on-object interaction' feature, which of the following ways can I NOT insert something that will allow the user to run a Q&A?",
    choices: [
      "Go to the Home menu and, in the Insert drop-down box, under AI visuals, click on Q&A.",
      "Go to Insert and add a Text Box. In the Format pane for the Text Box, change the 'Action' to Q&A.",
      "Go to Insert menu and click on Q&A.",
      "Go to Insert and click on Buttons, and then click on Q&A."
    ],
    correctAnswers: [1],
    explanation: "Text Boxes do not have an 'Action' option in their Format pane. Only Buttons, Shapes, and Images support Actions. Therefore, a Text Box cannot be configured to launch Q&A.",
    estimatedTimeSeconds: 90,
    tags: ["Q&A Visual", "Text Box", "Buttons", "Actions"]
  },
  {
    id: startId + 22,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Configure navigation for a report",
    commonTrap: "Thinking Sync Slicers is a button action",
    trapType: "Button Action Knowledge",
    question: "Which of these is NOT a valid Action for a Button?",
    choices: ["Back", "Bookmark", "Q&A", "Sync slicers"],
    correctAnswers: [3],
    explanation: "Valid Actions for buttons include: Back, Bookmark, Drill through, Page navigation, Q&A, and Web URL. Sync Slicers is a View menu feature, not a button action.",
    estimatedTimeSeconds: 60,
    tags: ["Buttons", "Actions", "Navigation"]
  },
  {
    id: startId + 23,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Enhance reports for usability and storytelling",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "understanding",
    examObjective: "Visualize and analyze the data > Configure drillthrough navigation",
    commonTrap: "Confusing drill-through with drill-down within a visual",
    trapType: "Drill Navigation Confusion",
    question: "What is an example of what a drill-through does?",
    choices: [
      "In a visual, the X-axis can change from Years to Quarters.",
      "You can go from a summary page to a detailed page.",
      "In a visual, the X-axis can change from Years to Years and Quarters.",
      "In a visual, the X-axis can change from showing all years to focusing on one particular year and showing Quarters."
    ],
    correctAnswers: [1],
    explanation: "Drill-through navigates from one report page to another (e.g., summary to detail). Drill-down changes hierarchy levels within the same visual.",
    estimatedTimeSeconds: 60,
    tags: ["Drill-through", "Report Navigation", "Pages"]
  },
  {
    id: startId + 24,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Putting SalesVolume into the Y Axis instead of Size",
    trapType: "Visual Field Placement",
    question: "I am creating a scatter chart. I want to change it into a bubble chart so that the bubble is bigger when SalesVolume is higher, and smaller when SalesVolume is lower. Where do I need to drag the SalesVolume field?",
    choices: [
      "Into the Size section.",
      "Into the Area section.",
      "Into the Y Axis.",
      "Into the Legend."
    ],
    correctAnswers: [0],
    explanation: "In a scatter/bubble chart, the Size field controls the size of each bubble. Placing SalesVolume in Size means higher values produce larger bubbles.",
    estimatedTimeSeconds: 60,
    tags: ["Bubble Chart", "Scatter Chart", "Size Field", "Visual Configuration"]
  },
  {
    id: startId + 25,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Putting Year in the Time Axis instead of Play Axis",
    trapType: "Visual Field Naming",
    question: "I want to animate a scatter chart, showing the result for individual years. Where do I need to put the Year field?",
    choices: [
      "In the Time Axis.",
      "In the Play Axis.",
      "In the Breakdown Axis.",
      "In the Legend."
    ],
    correctAnswers: [1],
    explanation: "The Play Axis in a scatter chart enables animation. When a field is placed in the Play Axis, you can click the Play button to animate the chart across each value (e.g., year).",
    estimatedTimeSeconds: 60,
    tags: ["Scatter Chart", "Play Axis", "Animation"]
  },
  {
    id: startId + 26,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Going to Format pane to deselect Cumulative Total instead of using Breakdown",
    trapType: "Visual Configuration Method",
    question: "I am creating a waterfall chart. It is currently showing a cumulative total. I want it to show each category individually, not cumulatively. What do I need to do?",
    choices: [
      "Add a field to the Category area.",
      "Add a field to the Y-axis area.",
      "Add a field to the Breakdown area.",
      "Go to the Format pane, to the Totals section, and deselect 'Cumulative Total'."
    ],
    correctAnswers: [2],
    explanation: "In a waterfall chart, adding a field to the Breakdown area shows each category separately rather than as a running cumulative total.",
    estimatedTimeSeconds: 75,
    tags: ["Waterfall Chart", "Breakdown", "Visual Configuration"]
  },
  {
    id: startId + 27,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Create reports",
    commonTrap: "Confusing AppSource with PowerBI.com marketplace",
    trapType: "Platform Knowledge",
    question: "What is the name of the marketplace where you download custom Power BI visuals?",
    choices: ["PowerBICenter", "AppSource", "VisualStudio", "AnalysisStore"],
    correctAnswers: [1],
    explanation: "Custom Power BI visuals are downloaded from Microsoft AppSource. You can access it directly from the Visualization pane in Power BI Desktop.",
    estimatedTimeSeconds: 45,
    tags: ["AppSource", "Custom Visuals", "Marketplace"]
  },
  {
    id: startId + 28,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "understanding",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Confusing conversion rate with completion rate",
    trapType: "Terminology",
    question: "A funnel chart shows that 100% of users start the first process, but only 71.5% complete the last process. What is this percentage called?",
    choices: ["The conversion rate", "The success rate", "The completion rate", "The checkout rate"],
    correctAnswers: [0],
    explanation: "The conversion rate in a funnel chart represents the percentage of users who complete the entire process from start to finish.",
    estimatedTimeSeconds: 45,
    tags: ["Funnel Chart", "Conversion Rate", "Analytics"]
  },
  {
    id: startId + 29,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Hard",
    questionStyle: "scenario",
    cognitiveLevel: "analysis",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Thinking the Category and Details sections behave identically for color assignment",
    trapType: "Treemap Color Behavior",
    question: "I am creating a treemap with RegionName in the Category section. I want to add Year into either the Category or the Details section. Which of the following statements is true about the color behavior?",
    choices: [
      "If Year is in either section, all rectangles for a particular RegionName will be different colors.",
      "If Year is in either section, all rectangles for a particular RegionName will be the same color.",
      "If Year is in the Category section, rectangles for the same RegionName will be the same color. If Year is in the Details section, they will be different colors.",
      "If Year is in the Category section, rectangles for the same RegionName will be different colors. If Year is in the Details section, they will be the same color."
    ],
    correctAnswers: [3],
    explanation: "In a treemap, fields in the Category section define color groupings. Adding Year to Category makes each Year a separate color group. Fields in the Details section break categories into sub-rectangles but share the parent category color.",
    estimatedTimeSeconds: 120,
    tags: ["Treemap", "Category", "Details", "Colors", "Visual Configuration"]
  },
  {
    id: startId + 30,
    type: "single",
    domain: "Model the data",
    subtopic: "Design and implement a data model",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Model the data > Configure table and column properties",
    commonTrap: "Looking in Report view Field pane or Modeling menu",
    trapType: "UI Navigation for Hierarchy",
    question: "I have created a hierarchy of Country - City - State. I realise it is in the wrong order. I need to move 'City' down. Where do I go to do that?",
    choices: [
      "In the Report view, I go to the Field pane.",
      "In the Report view, I go to the Modeling menu.",
      "In the Data view, I go to the Data pane.",
      "In the Model view, I click on the table and go to the Properties pane."
    ],
    correctAnswers: [3],
    explanation: "To reorder levels in a hierarchy, go to Model view, click on the table containing the hierarchy, find it in the Properties pane, and drag the levels to reorder them. Click 'Apply Level Changes' to confirm.",
    estimatedTimeSeconds: 75,
    tags: ["Hierarchy", "Model View", "Properties Pane", "Data Modeling"]
  },
  {
    id: startId + 31,
    type: "single",
    domain: "Model the data",
    subtopic: "Design and implement a data model",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Model the data > Configure table and column properties",
    commonTrap: "Using Data type instead of Data category for geographic fields",
    trapType: "Column Property Confusion",
    question: "In Power BI Desktop, which Column tools dropdown allows you to specify that a field relates to a geographic concept such as a country, county, state or province, postal code, or address?",
    choices: ["Summarization", "Data type", "Data category", "Geographical location"],
    correctAnswers: [2],
    explanation: "The Data category property in Column tools lets you classify a field as a geographic concept (Country, State, City, Postal code, etc.), which helps Power BI map visuals accurately.",
    estimatedTimeSeconds: 60,
    tags: ["Data Category", "Column Tools", "Geography", "Map Visual"]
  },
  {
    id: startId + 32,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "understanding",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Confusing heat map with bubble map",
    trapType: "Map Visual Type",
    question: "A map shows various location circles with a light red outside and a dark red inside. Some circles combine to form bigger, darker areas. What is this type of map called in Power BI?",
    choices: ["Bubble map", "Heat map", "Filled map", "ArcGIS"],
    correctAnswers: [1],
    explanation: "A heat map shows data density or intensity through color gradients. Overlapping circles that combine into darker areas is the heat map visual behavior in Power BI.",
    estimatedTimeSeconds: 60,
    tags: ["Heat Map", "Map Visual", "Geographic Visualization"]
  },
  {
    id: startId + 33,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Thinking 'Find' is a standard map control option",
    trapType: "Map Control Knowledge",
    question: "I can add or remove map controls by going to the Format pane, then Map settings - Controls. Which of the following is NOT a control I can add or remove?",
    choices: ["Auto zoom", "Navigation", "Selection", "Find"],
    correctAnswers: [3],
    explanation: "Available map controls include Auto zoom, Navigation, and Selection (lasso). 'Find' is not available — you cannot add a button to search for locations in the map visual.",
    estimatedTimeSeconds: 60,
    tags: ["Map Visual", "Format Pane", "Controls"]
  },
  {
    id: startId + 34,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Thinking Breakdown is part of a KPI (it is used in waterfall charts)",
    trapType: "Visual Component Knowledge",
    question: "Which of the following is NOT included in a KPI visual?",
    choices: ["Icons", "Trend axis", "Breakdown", "Callout value"],
    correctAnswers: [2],
    explanation: "KPI visuals include a Callout value (the main metric), Trend axis (shows progress over time), and Goal/Target. 'Breakdown' is a field used in waterfall charts, not KPIs.",
    estimatedTimeSeconds: 60,
    tags: ["KPI Visual", "Visual Components", "Waterfall Chart"]
  },
  {
    id: startId + 35,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Apply conditional formatting",
    commonTrap: "Choosing 'Field value' when no color column exists",
    trapType: "Conditional Formatting Type Selection",
    question: "I have a table showing quarterly data. I want to apply conditional formatting background colors: Spring = Green, Summer = Yellow, Autumn/Fall = Brown, Winter = White. I do not have a separate color column — the colors must come from the Quarter field itself. What Format style should I use?",
    choices: ["Gradient", "Rules", "Field value", "Data bar"],
    correctAnswers: [1],
    explanation: "Rules-based conditional formatting lets you define specific conditions (e.g., if field equals 'Spring', apply Green). 'Field value' would require a column that already stores color values. 'Gradient' works with numeric ranges.",
    estimatedTimeSeconds: 90,
    tags: ["Conditional Formatting", "Rules", "Table Visual"]
  },
  {
    id: startId + 36,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Thinking a Card shows a bar chart or icons",
    trapType: "Visual Capability",
    question: "Apart from the measure name, which of the following is shown in a Card visual?",
    choices: ["An area chart", "Icons", "A number", "A bar chart"],
    correctAnswers: [2],
    explanation: "A Card visual displays a single number (a measure value) along with the measure name. You can also show the First or Last value of a text field.",
    estimatedTimeSeconds: 45,
    tags: ["Card Visual", "Single Number", "Measures"]
  },
  {
    id: startId + 37,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Format and configure visuals",
    commonTrap: "Turning off Data labels instead of Callout value",
    trapType: "Format Pane Property Naming",
    question: "I have a gauge visual that shows '88.14K' in the middle of the gauge. I want to remove this figure. I click on the gauge and go to the Format pane. What should I turn off?",
    choices: ["Data labels", "Target label", "Callout value", "Title"],
    correctAnswers: [2],
    explanation: "The Callout value in a gauge visual is the large number displayed in the center of the gauge arc. Turning it off removes this number from the visual.",
    estimatedTimeSeconds: 60,
    tags: ["Gauge Visual", "Callout Value", "Format Pane"]
  },
  {
    id: startId + 38,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Use reference lines, error bars, and forecasting",
    commonTrap: "Thinking 'By formula' is a valid error bar type",
    trapType: "Feature Capability Knowledge",
    question: "I want to add an error bar to my line chart. After enabling Error bars in the Format pane, I go to the 'Type' dropdown. Which of these is NOT a possible option?",
    choices: ["By field", "By percentage", "By formula", "By percentile"],
    correctAnswers: [2],
    explanation: "Error bar types in Power BI include: By field, By percentage, By percentile, and By standard deviation. 'By formula' is not a valid option.",
    estimatedTimeSeconds: 75,
    tags: ["Error Bars", "Line Chart", "Format Pane", "Analytics"]
  },
  {
    id: startId + 39,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "analysis",
    examObjective: "Visualize and analyze the data > Configure export settings",
    commonTrap: "Thinking all columns in the dataset are exported",
    trapType: "Export Behavior",
    question: "I have a dataset with columns: Year, Month, Sick Leave Hours, and Vacation Hours. My clustered column chart shows Sick Leave Hours by Month. I click '...' on the visual and select 'Export Data'. How many columns does this exported data have?",
    choices: [
      "1 (Sick Leave Hours)",
      "2 (Month and Sick Leave Hours)",
      "3 (Year, Month and Sick Leave Hours)",
      "4 (Year, Month, Sick Leave Hours and Vacation Hours)"
    ],
    correctAnswers: [1],
    explanation: "Exporting data from a visual exports only the data that makes up that visual. Since the chart shows Sick Leave Hours by Month, only those two columns are exported.",
    estimatedTimeSeconds: 90,
    tags: ["Export Data", "Visual Data", "Clustered Column Chart"]
  },
  {
    id: startId + 40,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Configure export settings",
    commonTrap: "Thinking it exports as Excel",
    trapType: "Export Format",
    question: "I click on the '...' to the top-right of a clustered column chart visual and click 'Export Data'. What format does it export as?",
    choices: [
      "Excel workbook",
      "PDF document",
      "PowerPoint presentation",
      "Comma Separated Values (CSV) file"
    ],
    correctAnswers: [3],
    explanation: "Exporting visual data from a Power BI Desktop report downloads a CSV file. You can then import it into Excel or other tools.",
    estimatedTimeSeconds: 45,
    tags: ["Export Data", "CSV", "Visual Export"]
  },
  {
    id: startId + 41,
    type: "single",
    domain: "Model the data",
    subtopic: "Create model calculations by using DAX",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Model the data > Create model calculations by using DAX > Create a measure by using quick measures",
    commonTrap: "Using the Date Hierarchy level instead of the base date field",
    trapType: "Quick Measure Date Field Selection",
    question: "I want to create a Quick Measure that calculates the year-to-date total of SalesVolume based on the OrderDate field. The OrderDate has a hierarchy with Year, Quarter, Month, and Day. After selecting 'Year-to-date total', what fields should I add and where?",
    choices: [
      "Base value = OrderDate / Date = SalesVolume",
      "Base value = SalesVolume / Date = OrderDate - Date Hierarchy - Day",
      "Base value = SalesVolume / Date = OrderDate - Date Hierarchy - Year",
      "Base value = SalesVolume / Date = OrderDate"
    ],
    correctAnswers: [3],
    explanation: "For a YTD Quick Measure, 'Base value' is the measure to total (SalesVolume), and 'Date' should be the date field itself (OrderDate), not a hierarchy level. The hierarchy levels are not date fields.",
    estimatedTimeSeconds: 90,
    tags: ["Quick Measures", "YTD", "DAX", "Date Intelligence"]
  },
  {
    id: startId + 42,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Create a narrative visual with Copilot",
    commonTrap: "Right-clicking and selecting 'Smart Narrative' instead of 'Summarize'",
    trapType: "Feature Naming",
    question: "I have a page with just one visual and want to create a Smart Narrative. Besides going to Home or Insert to add the visual, what other way can I create one?",
    choices: [
      "Click on the ... next to the visual, and go to Smart Narrative.",
      "Click on the ... next to the visual, and go to Summarize.",
      "Right-hand click on the visual, and go to Smart Narrative.",
      "Right-hand click on the visual, and go to Summarize."
    ],
    correctAnswers: [3],
    explanation: "Right-clicking on a visual and selecting 'Summarize' creates a Smart Narrative visual linked to that visual. The '...' menu does not contain a Smart Narrative or Summarize option.",
    estimatedTimeSeconds: 75,
    tags: ["Smart Narrative", "AI Visuals", "Summarize"]
  },
  {
    id: startId + 43,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "understanding",
    examObjective: "Visualize and analyze the data > Use grouping, binning, and clustering",
    commonTrap: "Thinking 'Include Other group' is available for Bin type",
    trapType: "Group Type Knowledge",
    question: "I create a group by right-clicking a field and selecting 'New group'. The Groups dialog box appears. Which of the following statements is true about the Groups dialog box?",
    choices: [
      "When 'Group type' is 'Bin', it divides numerical values into similarly-sized ranges.",
      "When 'Group type' is 'Bin', I can check 'Include Other group'.",
      "'Group type' is 'List' is primarily used for fields which contain numerical values.",
      "For fields which contain text values, you can choose either 'Group type' to be 'List' or 'Bin'."
    ],
    correctAnswers: [0],
    explanation: "Bin groups divide numerical values into equally-sized ranges. You can then set 'Bin size' or 'Number of bins'. 'Include Other group' is only available for List type, and Bin type requires numerical fields.",
    estimatedTimeSeconds: 90,
    tags: ["Groups", "Binning", "Clustering", "Analytics"]
  },
  {
    id: startId + 44,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "analysis",
    examObjective: "Visualize and analyze the data > Detect outliers and anomalies",
    commonTrap: "Thinking higher sensitivity means fewer anomalies",
    trapType: "Anomaly Detection Logic",
    question: "I have a line chart with 'Find anomalies' turned on. Sensitivity is at 50% and 10 points are currently highlighted as anomalous. If I change sensitivity to 80%, which outcome is most likely?",
    choices: [
      "The number of anomalous points will go down to 9 or less.",
      "The number of anomalous points will remain at 10, as sensitivity does not affect this.",
      "The number of anomalous points will go up to 11 or more.",
      "You cannot change the sensitivity directly — you must change the Expected Range instead."
    ],
    correctAnswers: [2],
    explanation: "Higher sensitivity means the 'normal' band becomes narrower, so more data points fall outside it and are flagged as anomalous. Increasing sensitivity from 50% to 80% will likely increase the number of anomalous points.",
    estimatedTimeSeconds: 90,
    tags: ["Anomaly Detection", "Sensitivity", "Line Chart", "Analytics"]
  },
  {
    id: startId + 45,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Use grouping, binning, and clustering",
    commonTrap: "Right-clicking on a field in the Data pane instead of using the visual menu",
    trapType: "Clustering Feature Location",
    question: "I have a scatter chart and want to ask Power BI to 'automatically find clusters' and divide the plots into 5 clusters. Where do I go to do this?",
    choices: [
      "Right-hand click on the date field in the Values section in the Build a Visual pane.",
      "Right-hand click on the SalesVolume field in the Data pane.",
      "Click on the ... in the top-right hand corner of the visual.",
      "Right-hand click anywhere on the scatter chart."
    ],
    correctAnswers: [2],
    explanation: "Automatic cluster detection for a scatter chart is accessed via the '...' (more options) menu in the top-right corner of the visual. From there, select 'Automatically find clusters'.",
    estimatedTimeSeconds: 75,
    tags: ["Clustering", "Scatter Chart", "AI Analytics", "More Options"]
  },
  {
    id: startId + 46,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "analysis",
    examObjective: "Visualize and analyze the data > Select an appropriate visual",
    commonTrap: "Using a line or stacked column chart for outlier detection",
    trapType: "Best Visual for Analysis",
    question: "Which visualization technique is best suited for identifying outliers in a dataset of employee expenses?",
    choices: [
      "Using a Stacked column chart, with Year and Month in the X-axis, and Expense in the Y-axis.",
      "Using a Line chart, with Year and Month in the X-axis, and Expense in the Y-axis.",
      "Using a Scatter chart, with the Date Hierarchy in the X-axis, Expense in the Y-axis, and Person ID in the Legend.",
      "Using a Pie chart, with the Date Hierarchy in the Legend, and Expense in the Values."
    ],
    correctAnswers: [2],
    explanation: "A scatter chart with Person ID in the Legend shows individual data points per person, making it easy to identify outliers. The Date Hierarchy in the X-axis allows drilling into specific time periods.",
    estimatedTimeSeconds: 90,
    tags: ["Scatter Chart", "Outliers", "Visual Selection", "Analytics"]
  },
  {
    id: startId + 47,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Create reports",
    difficulty: "Medium",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Choose when to use a paginated report",
    commonTrap: "Thinking Excel can be used as a data source in Report Builder",
    trapType: "Paginated Report Data Sources",
    question: "I want to create a paginated report. Which of the following data sources can I NOT connect to in Power BI Report Builder?",
    choices: [
      "Microsoft Azure SQL Database",
      "Microsoft Excel",
      "Microsoft SQL Server Analysis Services",
      "Oracle Database"
    ],
    correctAnswers: [1],
    explanation: "Power BI Report Builder (for paginated reports) connects to online database sources like Azure SQL, SQL Server Analysis Services, and Oracle. Microsoft Excel is not supported as a data source.",
    estimatedTimeSeconds: 75,
    tags: ["Paginated Reports", "Report Builder", "Data Sources"]
  },
  {
    id: startId + 48,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Use the Analyze feature in Power BI",
    commonTrap: "Right-clicking on the high bar (2007) instead of the low bar (2008)",
    trapType: "Analyze Direction",
    question: "I have a bar chart showing Year on the X-axis and Sales Volume on the Y-axis. Sales is high in 2007 and low in 2008. I want Power BI to explain why there is this difference. What should I do?",
    choices: [
      "Right-hand click the bar in 2007 and select Analyze - Explain the decrease.",
      "Right-hand click the visual and select Summarize.",
      "Right-hand click the bar in 2008 and select Analyze - Explain the decrease.",
      "Right-hand click the visual and select Explain the distribution."
    ],
    correctAnswers: [2],
    explanation: "To explain a decrease, right-click on the lower value (2008 bar) and select Analyze > Explain the decrease. Power BI will identify factors contributing to the drop from 2007 to 2008.",
    estimatedTimeSeconds: 75,
    tags: ["Analyze Feature", "Explain Decrease", "AI Analytics", "Bar Chart"]
  },
  {
    id: startId + 49,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Visualize and analyze the data > Use AI visuals",
    commonTrap: "Confusing Expand by (Key Influencers) with Decomposition Tree sections",
    trapType: "AI Visual Section Confusion",
    question: "Which of the following sections is NOT used in the AI Decomposition Tree visual?",
    choices: ["Analyze", "Explain by", "Expand by"],
    correctAnswers: [2],
    explanation: "'Expand by' is used in the Key Influencers visual to show what a metric expands to. The Decomposition Tree uses 'Analyze' (the metric) and 'Explain by' (the dimensions to break down by).",
    estimatedTimeSeconds: 75,
    tags: ["Decomposition Tree", "AI Visuals", "Key Influencers"]
  },
  {
    id: startId + 50,
    type: "single",
    domain: "Visualize and analyze the data",
    subtopic: "Identify patterns and trends",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Visualize and analyze the data > Use AI visuals",
    commonTrap: "Dragging Region Name into Analyze or Expand by",
    trapType: "Key Influencers Field Placement",
    question: "I have a Key Influencers visual that shows the effect of year and month on Sales Volume. I also want to see the effect of Region Name on Sales Volume. What should I do?",
    choices: [
      "Drag 'Region Name' into the Analyze section.",
      "Drag 'Region Name' into the 'Explain by' section.",
      "Drag 'Region Name' into the 'Expand by' section.",
      "Remove Date from 'Explain by' first, then drag 'Region Name' into the 'Explain by' section."
    ],
    correctAnswers: [1],
    explanation: "In Key Influencers, the 'Explain by' section contains the dimensions that may influence the metric. You can add multiple fields; removing existing fields is not required.",
    estimatedTimeSeconds: 75,
    tags: ["Key Influencers", "AI Visuals", "Explain By", "Region"]
  },
  {
    id: startId + 51,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Profile and clean the data",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Prepare the data > Transform and load the data",
    commonTrap: "Thinking Remove Range of Rows is available like Keep Range of Rows",
    trapType: "Power Query Feature Knowledge",
    question: "Which of these is NOT an option when looking at Home - Remove Rows in Power Query Editor?",
    choices: ["Remove Top Rows", "Remove Bottom Rows", "Remove Range of Rows", "Remove Blank Rows"],
    correctAnswers: [2],
    explanation: "In Power Query, you can use Home > Keep Rows > Keep Range of Rows, but there is no 'Remove Range of Rows' option. You can Remove Top Rows, Remove Bottom Rows, Remove Duplicates, Remove Blank Rows, and Remove Errors.",
    estimatedTimeSeconds: 75,
    tags: ["Power Query", "Remove Rows", "Transform"]
  },
  {
    id: startId + 52,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "analysis",
    examObjective: "Prepare the data > Transform and load the data",
    commonTrap: "Thinking 'Go to Column' removes the column",
    trapType: "Power Query Feature Purpose",
    question: "In the Power Query Editor, I want to remove a column called Comments. Which of the following options could NOT, by itself, remove the column?",
    choices: [
      "In the Home tab, click on Choose Columns - Choose Columns",
      "In the Home tab, click on Choose Columns - Go to Column",
      "In the Home tab, click on Remove Columns - Remove Column",
      "In the Home tab, click on Remove Columns - Remove Other Columns"
    ],
    correctAnswers: [1],
    explanation: "'Go to Column' simply highlights/scrolls to a column — it does not remove it. 'Choose Columns' lets you select which columns to keep (deselecting Comments removes it). 'Remove Column' and 'Remove Other Columns' can also remove it.",
    estimatedTimeSeconds: 75,
    tags: ["Power Query", "Remove Columns", "Choose Columns", "Go to Column"]
  },
  {
    id: startId + 53,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Medium",
    questionStyle: "direct",
    cognitiveLevel: "understanding",
    examObjective: "Prepare the data > Transform and load the data > Identify when to use reference or duplicate queries",
    commonTrap: "Thinking Duplicate and Reference behave the same way",
    trapType: "Duplicate vs Reference",
    question: "What is the difference between Duplicating a query and Referencing it?",
    choices: [
      "Duplicating a query copies the current query. Referencing a query only copies the location of its data source.",
      "Duplicating a query copies the current query. Referencing a query creates a link to the query, so if the original changes, the reference is updated.",
      "Referencing a query copies the current query. Duplicating a query only copies the location of its data source.",
      "Referencing a query copies the current query. Duplicating a query creates a link, so if the original changes, the duplicate is updated."
    ],
    correctAnswers: [1],
    explanation: "Duplicate creates an independent copy — changes to the original don't affect the duplicate. Reference creates a dependent link — if the original query changes, the referenced query reflects those changes.",
    estimatedTimeSeconds: 90,
    tags: ["Power Query", "Duplicate Query", "Reference Query", "Query Dependencies"]
  },
  {
    id: startId + 54,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Prepare the data > Transform and load the data",
    commonTrap: "Using underscore or dash notation instead of dot notation",
    trapType: "M Language Syntax",
    question: "The Power Query Editor uses a language called 'M'. When you add an applied step, it is translated into M formulas. Which of the following is in the correct format to be an M function?",
    choices: ["Text-Proper", "Text_Proper", "TextProper", "Text.Proper"],
    correctAnswers: [3],
    explanation: "M functions use dot notation with two parts separated by a dot (e.g., Text.Proper, Text.Upper, Date.Year). All words start with a capital letter and there are no spaces.",
    estimatedTimeSeconds: 60,
    tags: ["M Language", "Power Query", "M Functions", "Syntax"]
  },
  {
    id: startId + 55,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "understanding",
    examObjective: "Prepare the data > Transform and load the data > Select appropriate column data types",
    commonTrap: "Thinking the 'any' type shows only ABC or only 123",
    trapType: "Data Type Symbol Knowledge",
    question: "I have imported some data. In one column, Power Query Editor cannot determine what data type it should be. What does the symbol for the default or 'any' data type contain?",
    choices: ["ABC", "123", "A globe", "ABC / 123"],
    correctAnswers: [3],
    explanation: "The 'any' or unknown data type is represented by the symbol showing both 'ABC' and '123' together, indicating the column could contain any type of data.",
    estimatedTimeSeconds: 60,
    tags: ["Data Types", "Power Query", "Any Data Type", "Column Properties"]
  },
  {
    id: startId + 56,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Prepare the data > Transform and load the data",
    commonTrap: "Thinking 'By Word' is a valid split option (it isn't — use 'By Delimiter' with space instead)",
    trapType: "Power Query Split Column Options",
    question: "I want to split a text field. I go to Home - Split Column. Which of the following is NOT a valid option?",
    choices: ["By Number of Characters", "By Positions", "By Word", "By Lowercase to Uppercase"],
    correctAnswers: [2],
    explanation: "Split Column options include: By Delimiter, By Number of Characters, By Positions, By Lowercase to Uppercase, By Uppercase to Lowercase, and By Digit to Non-Digit. 'By Word' is not valid — use 'By Delimiter' with a space character instead.",
    estimatedTimeSeconds: 75,
    tags: ["Power Query", "Split Column", "Transform", "Text Transformation"]
  },
  {
    id: startId + 57,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Prepare the data > Transform and load the data",
    commonTrap: "Clicking on the filter drop-down instead of deleting the Applied Step",
    trapType: "Applied Steps Behavior",
    question: "I have an Employee dataset in Power Query Editor. I filtered the Town column to show only Boston employees, then sorted by Last Name ascending. I now want to re-filter to show only New York employees. What is the easiest way?",
    choices: [
      "Click on the filter next to Town. Unselect Boston and select New York.",
      "Delete the last Applied Step. Click on the filter next to Town and select New York.",
      "Delete the current query. Reload the data. Click on the filter next to Town and select New York.",
      "Close and Apply. In Power BI Desktop Data view, click the filter next to Town and select New York."
    ],
    correctAnswers: [1],
    explanation: "The last Applied Step is the sort step. Deleting it makes the filter step the current step, which you can then edit to change the filter value to New York. You could also delete both steps if needed.",
    estimatedTimeSeconds: 90,
    tags: ["Power Query", "Applied Steps", "Filters", "Query Editing"]
  },
  {
    id: startId + 58,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Prepare the data > Get or connect to data",
    commonTrap: "Using Merge Files or Append Files instead of Combine Files",
    trapType: "Power Query File Operations",
    question: "I have 20 files of the same format in a Windows folder. How can I easily get the data from all of these files in one query?",
    choices: [
      "Go to Home - Merge Files",
      "Go to Home - Append Files",
      "Go to Home - Combine Files",
      "Go to Home - Load Files"
    ],
    correctAnswers: [2],
    explanation: "In Power Query, Home > Combine Files lets you combine multiple files from a folder into a single query. You connect to the folder first, then use Combine Files to merge all files of the same format.",
    estimatedTimeSeconds: 60,
    tags: ["Power Query", "Combine Files", "Folder Connection", "Data Sources"]
  },
  {
    id: startId + 59,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "analysis",
    examObjective: "Prepare the data > Transform and load the data > Merge and append queries",
    commonTrap: "Thinking appended queries lose columns that don't match, or error on type mismatch",
    trapType: "Append Query Behavior",
    question: "Query1 has columns: Date, Subject, Comments (Subject is text). Query2 has columns: Date, Cost, Comments (Cost is decimal). I append these queries into a new query. How many columns does the new query have?",
    choices: [
      "3: Date, Subject and Comments.",
      "4: Date, Subject, Comments and Cost.",
      "6: Date, Subject, Comments, Date, Cost and Comments.",
      "This results in an error, as the second column has two different data types."
    ],
    correctAnswers: [1],
    explanation: "Appending queries stacks rows and creates a union of all columns. Unique columns from each query are added — Date and Comments overlap, while Subject and Cost are unique. Null values fill where a column doesn't exist in one query.",
    estimatedTimeSeconds: 90,
    tags: ["Power Query", "Append Queries", "Columns", "Union"]
  },
  {
    id: startId + 60,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Prepare the data > Transform and load the data > Merge and append queries",
    commonTrap: "Right-clicking the header or clicking the table icon instead of the expand icon",
    trapType: "Merged Query Expansion",
    question: "I have merged a 'CD Categorisation' query (with Path and CD Type columns) into a 'CDs' query. The merged column shows 'Table' for each row. I want to see the CD Type column for all rows. What should I do?",
    choices: [
      "Click on the Table icon in the top-left hand corner.",
      "Right-hand click on the 'CD Categorisation' header and select 'Expand'.",
      "Click on the icon in the top-right hand corner of the column header which has two arrows, one pointing left and one pointing right.",
      "Click on the word 'Table' in the data section."
    ],
    correctAnswers: [2],
    explanation: "After a merge, the nested table column shows a double-arrow expand icon in the top-right of the column header. Clicking it lets you select which columns from the merged table to expand into the main query.",
    estimatedTimeSeconds: 90,
    tags: ["Power Query", "Merge Queries", "Expand", "Nested Tables"]
  },
  {
    id: startId + 61,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Medium",
    questionStyle: "direct",
    cognitiveLevel: "analysis",
    examObjective: "Prepare the data > Transform and load the data > Merge and append queries",
    commonTrap: "Thinking you can merge three queries simultaneously",
    trapType: "Merge Query Limitation",
    question: "Which of these statements about merging queries is NOT correct?",
    choices: [
      "I can merge three queries together at the same time.",
      "I can append three queries together at the same time.",
      "I can combine three files together at the same time."
    ],
    correctAnswers: [0],
    explanation: "Merge Queries can only merge two queries at a time. To merge three queries, you must merge two first, then merge the result with the third. Append and Combine Files both support multiple sources at once.",
    estimatedTimeSeconds: 75,
    tags: ["Power Query", "Merge Queries", "Limitations", "Append"]
  },
  {
    id: startId + 62,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "understanding",
    examObjective: "Prepare the data > Transform and load the data > Merge and append queries",
    commonTrap: "Confusing Left Outer with Inner join",
    trapType: "Join Type Behavior",
    question: "In Power Query Editor, I merge Query1 with Query2 (Query1 on top). The Join Kind defaults to 'Left Outer'. What does a Left Outer join retrieve?",
    choices: [
      "It retrieves all rows from both Query1 and Query2.",
      "It retrieves only the rows from Query1 and Query2 that match.",
      "It retrieves all rows from Query2, and those rows in Query1 that match.",
      "It retrieves all rows from Query1, and those rows in Query2 that match."
    ],
    correctAnswers: [3],
    explanation: "Left Outer join returns all rows from the left (first) table — Query1 — and only matching rows from the right table — Query2. Non-matching rows from Query2 are excluded; non-matching Query1 rows get null values.",
    estimatedTimeSeconds: 90,
    tags: ["Power Query", "Merge Queries", "Left Outer Join", "Join Types"]
  },
  {
    id: startId + 63,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Easy",
    questionStyle: "direct",
    cognitiveLevel: "recall",
    examObjective: "Prepare the data > Transform and load the data > Pivot, unpivot, and transpose data",
    commonTrap: "Thinking the columns are called 'Key' and 'Data' or 'Column' and 'Row'",
    trapType: "Unpivot Column Naming",
    question: "I am going to use Transform - Unpivot. It will remove several columns and create two new columns. What are those two new columns called?",
    choices: ["Heading and Total", "Attribute and Value", "Column A and Column B", "Key and Data"],
    correctAnswers: [1],
    explanation: "Transform > Unpivot Columns creates two new columns: 'Attribute' (the headers of the removed columns) and 'Value' (the data values that were in those columns).",
    estimatedTimeSeconds: 60,
    tags: ["Power Query", "Unpivot", "Transform", "Attribute", "Value"]
  },
  {
    id: startId + 64,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Hard",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Prepare the data > Transform and load the data > Pivot, unpivot, and transpose data",
    commonTrap: "Not removing unnecessary columns before pivoting",
    trapType: "Pivot Column Preparation",
    question: "My dataset has columns: Date, Region, Area, AreaCode, SalesVolume. Regions are Northeast, Midwest, South, West. I want to pivot so that Date goes down and each Region becomes a separate column summing SalesVolume (5 total columns). What must I do BEFORE using Transform - Pivot Column?",
    choices: [
      "Remove Area and AreaCode columns.",
      "Move the SalesVolume column next to the Region column.",
      "Nothing — you can select which columns to show after pivoting.",
      "Highlight the Date, Region and SalesVolume columns."
    ],
    correctAnswers: [0],
    explanation: "Before pivoting, the dataset should only contain the columns you want to use in the pivot. All other columns (Area, AreaCode) must be removed first, otherwise Power Query tries to aggregate them and the result will not be what you expect.",
    estimatedTimeSeconds: 90,
    tags: ["Power Query", "Pivot Column", "Transform", "Data Preparation"]
  },
  {
    id: startId + 65,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Transform and load the data",
    difficulty: "Medium",
    questionStyle: "scenario",
    cognitiveLevel: "application",
    examObjective: "Prepare the data > Transform and load the data > Pivot, unpivot, and transpose data",
    commonTrap: "Selecting 'Date' as the Values Column instead of 'SalesVolume'",
    trapType: "Pivot Column Values Selection",
    question: "My dataset has columns: Date, Region, SalesVolume. Regions are Northeast, Midwest, South, West. I want Date down the left side and each Region as a column with the sum of SalesVolume (5 total columns). How do I do this?",
    choices: [
      "Go to the Region column. Click on Transform - Pivot Column. Select 'Date' as the 'Values Column'.",
      "Go to the Region column. Click on Transform - Unpivot Column. Select 'Date' as the 'Values Column'.",
      "Go to the Region column. Click on Transform - Unpivot Column. Select 'SalesVolume' as the 'Values Column'.",
      "Go to the Region column. Click on Transform - Pivot Column. Select 'SalesVolume' as the 'Values Column'."
    ],
    correctAnswers: [3],
    explanation: "To pivot, select the Region column and use Transform > Pivot Column. The 'Values Column' should be SalesVolume (the field to aggregate). The unique values of Region become new column headers.",
    estimatedTimeSeconds: 90,
    tags: ["Power Query", "Pivot Column", "Transform", "Values Column"]
  },
  {
    id: startId + 66,
    type: "single",
    domain: "Prepare the data",
    subtopic: "Profile and clean the data",
    difficulty: "Easy",
    questionStyle: "scenario",
    cognitiveLevel: "understanding",
    examObjective: "Prepare the data > Profile and clean the data > Resolve inconsistencies, unexpected or null values",
    commonTrap: "Thinking Fill Down only fills one blank cell, or fills the entire column with the top value",
    trapType: "Fill Down Behavior",
    question: "I have a column with values: Description, First Description, null, null, Second Description, null, null. I click on Transform - 'Fill Down'. What does it do and what is the final result?",
    choices: [
      "The entire column is overwritten by the top-most value. Result: Description, Description, Description, Description, Description, Description, Description.",
      "A value in one cell gets copied down to fill in any blank (null) cells. Result: Description, First Description, First Description, First Description, Second Description, Second Description, Second Description.",
      "A value in one cell gets copied down to only one blank cell underneath. Result: Description, First Description, First Description, null, Second Description, Second Description, null."
    ],
    correctAnswers: [1],
    explanation: "Fill Down replaces null values with the last non-null value above them. Each non-null value 'fills down' until the next non-null value. It does not overwrite existing non-null values.",
    estimatedTimeSeconds: 75,
    tags: ["Power Query", "Fill Down", "Null Values", "Transform"]
  }
]

const combined = [...existing, ...newQuestions]
writeFileSync(qPath, JSON.stringify(combined, null, 2))
console.log(`✅ Added ${newQuestions.length} questions (IDs ${startId}–${startId + newQuestions.length - 1}) | 📊 Total questions: ${combined.length}`)
